blog/urls.py
from django.urls import path


from .views import (
    #blog_list_view,
    #blog_detail_view,
    ArticleCreateView,
    ArticleDetailView,
    ArticleListView,
    ArticleUpdateView,
    ArticleDeleteView,
    )

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='article-list'),
    path('create/', ArticleCreateView.as_view(), name='article-create'),
    path('<int:id>/delete/', ArticleDeleteView.as_view(), name='article-delete'),
    path('<int:id>/update/', ArticleUpdateView.as_view(), name='article-update'),
    path('<int:id>/', ArticleDetailView.as_view(), name='article-detail'),
]

products/urls.py
from django.urls import path


from .views import (
    product_list_view,
    product_create_view,
    product_detail_view,
    product_update_view,
    product_delete_view,
    )

app_name = 'products'
urlpatterns = [
    path('', product_list_view, name='product-list'),
    path('create/', product_create_view, name='product-create'),
    path('<int:id>/', product_detail_view, name='product-detail'),
    path('<int:id>/update/', product_update_view, name='product-update'),
    path('<int:id>/delete/', product_delete_view, name='product-delete'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, contact_view, about_view

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('products/', include('products.urls')),
    path('blog/', include('blog.urls')),
    path('courses/', include('courses.urls')),

    path('admin/', admin.site.urls),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About</h1>
<p>This is a Template.</p>

<p>{{ my_text }}</p>
<p>{{ my_number }}</p>

<ul>
{% for item in my_list %}
    {% if item == 1 %}
    <li>{{ forloop.counter }} - {{ item|add:42 }}</li>
    {% elif item == 'Abc' %}
        <li>This is not a network</li>
    {% else %}
        <li>{{ forloop.counter }} - {{ item }}</li>
    {% endif %}
{% endfor %}
</ul>

{% endblock content %}
    

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Try Django</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container-fluid">
        {% block content %}
        replace me
        {% endblock content %}
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>Contact</h1>
<p>This is a Template.</p>

{% endblock content %}
    

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Hello World!</h1>
<p>This is a Template.</p>  
{% endblock content %}
    

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">Try Django</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		<div class="navbar-nav">
			<a class="nav-item nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
			<a class="nav-item nav-link" href="{% url 'products:product-create' %}">Create</a>
			<a class="nav-item nav-link" href="{% url 'products:product-list' %}">List</a>
			<a class="nav-item nav-link" href="{% url 'contact' %}">Contact</a>
			<a class="nav-item nav-link" href="{% url 'about' %}">About</a>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Blog
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="{% url 'articles:article-list' %}">Lista</a>
					<a class="dropdown-item" href="{% url 'articles:article-create' %}">Create</a>
				</div>
			</li>
		</div>
	</div>
</nav>